### ISSUE TITLE
change include paths for spookyhash files

### ISSUE THREAD

**Issue by mckellyln** [centaurean/density#44]
Can we change the include paths for spookyhash includes in

block_encode.h
block_decode.h

to not have the hardcoded 

spookyhash/src

directory ?  We can add to the compiler -I path to find these files.  This makes for adding density to an existing application easier as we do not have to edit the files for each new release.

**Comment by gpnuma** [comment]
What you want to do is have spookyhash and density in your own directories that's correct ?
Remember though that density is performing at its peak when compiled with clang, I would actually advise to compile it as a static library using clang on your platform and then linking to it, instead of merging all the files in a bigger project.

**Comment by gpnuma** [comment]
Fixed in c4a087c322287642efe211d5aa7bc06c5ac6d88d
